---
- name: Enable ntpd in rc.conf
  service:
    name: ntpd
    enabled: yes
  notify: restart ntpd
  tags: ntpd

- name: Disable public use of ntpd
  copy:
    content: |
      server 0.freebsd.pool.ntp.org iburst
      server 1.freebsd.pool.ntp.org iburst
      server 2.freebsd.pool.ntp.org iburst
      restrict default kod nomodify notrap nopeer noquery
      restrict -6 default kod nomodify notrap nopeer noquery
      restrict 127.0.0.1
      restrict -6 ::1
      restrict 127.127.1.0
    dest: /etc/ntp.conf
  notify: restart ntpd
  tags: ntpd
